[env:esp32s3]
platform = espressif32
framework = arduino
board = esp32-s3-devkitc-1
build_src_filter = +<main.cpp>
monitor_speed = 115200
upload_speed = 115200
build_type = debug
debug_tool = esp-builtin
debug_speed = 5000
debug_init_break = tbreak setup
upload_port = COM36
monitor_port = COM36
