[data]
kitId=0

; [env:uno]
; platform = atmelavr
; board = uno
; framework = arduino
; build_src_filter = +<uno0.cpp>

[env:esp32s3]
platform = espressif32
framework = arduino
board = esp32-s3-devkitc-1

debug_tool = esp-builtin
debug_init_break = tbreak setup
debug_speed = 12000

build_flags = -g -Og -DCORE_DEBUG_LEVEL=5

upload_protocol = esp-builtin ; Caso use debug (USB JTAG integrado)
; upload_protocol = esptool ; Caso use Wokwi ou a ESP direto
; upload_protocol = espota ; Caso use OTA
upload_port = inindkit${data.kitId}.local

monitor_speed = 115200

lib_deps = 

build_src_filter = +<esp0.cpp>